const DEFAULT_MARKET_WATCHLIST_TEMPLATES = [
  {
    key: 'nifty_50_top_10',
    name: 'Nifty 50 Top 10',
    order: 10,
    symbolLimit: 10,
    preferredSymbols: [
      'NSE:RELIANCE',
      'NSE:HDFCBANK',
      'NSE:ICICIBANK',
      'NSE:TCS',
      'NSE:INFY',
      'NSE:SBIN',
      'NSE:ITC',
      'NSE:AXISBANK',
      'NSE:LT',
      'NSE:KOTAKBANK',
    ],
    selector: {
      segments: ['EQUITY'],
      exchanges: ['NSE'],
      symbolPrefixes: ['NSE:'],
    },
  },
  {
    key: 'comex_top_10',
    name: 'COMEX Top 10',
    order: 20,
    symbolLimit: 10,
    preferredSymbols: [
      'XAUUSD',
      'XAGUSD',
      'WTICOUSD',
      'BRENTUSD',
      'NATGASUSD',
      'COPPERUSD',
      'XPTUSD',
      'XPDUSD',
      'CL1!',
      'NG1!',
    ],
    selector: {
      bucket: 'COMEX',
    },
  },
  {
    key: 'currency_top_10',
    name: 'Currency Top 10',
    order: 30,
    symbolLimit: 10,
    preferredSymbols: [
      'USDINR',
      'EURINR',
      'GBPINR',
      'JPYINR',
      'EURUSD',
      'GBPUSD',
      'USDJPY',
      'AUDUSD',
      'NZDUSD',
      'USDCAD',
    ],
    selector: {
      bucket: 'FOREX',
      segments: ['CURRENCY', 'FOREX'],
      exchanges: ['FOREX', 'CDS', 'BCD'],
    },
  },
  {
    key: 'indices_top_10',
    name: 'Indices Top 10',
    order: 40,
    symbolLimit: 10,
    preferredSymbols: [
      'NSE:NIFTY 50-INDEX',
      'NSE:NIFTY BANK-INDEX',
      'NSE:NIFTY FIN SERVICE-INDEX',
      'NSE:INDIA VIX',
      'NSE:NIFTY MID SELECT-INDEX',
      'NSE:NIFTY MIDCAP 100-INDEX',
      'NSE:NIFTY NEXT 50-INDEX',
      'NSE:NIFTY 100-INDEX',
      'NSE:NIFTY 200-INDEX',
      'NSE:SENSEX-INDEX',
    ],
    selector: {
      segments: ['INDICES'],
      symbolIncludes: ['-INDEX'],
      symbolPrefixes: ['NSE:NIFTY'],
      nameIncludes: ['INDEX'],
    },
  },
  {
    key: 'futures_top_10',
    name: 'Futures Top 10',
    order: 50,
    symbolLimit: 10,
    preferredSymbols: [
      'NIFTY',
      'BANKNIFTY',
      'FINNIFTY',
      'MIDCPNIFTY',
      'RELIANCE',
      'HDFCBANK',
      'ICICIBANK',
      'SBIN',
      'TCS',
      'INFY',
    ],
    selector: {
      segments: ['FNO'],
      exchanges: ['NFO'],
      symbolIncludes: ['FUT'],
      nameIncludes: ['FUTURE'],
    },
  },
];

export {
  DEFAULT_MARKET_WATCHLIST_TEMPLATES,
};

